name: ProjetCmake

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Cmake Tests
      run: |
        cmake -S . -B build
        cmake --build build
        cd build
        ctest

    - name: Install Doxygen
      run: sudo apt-get install -y doxygen 

    - name: Generate documentation
      run: doxygen Doxyfile

    - name: Deploy documentation to GitHub Pages
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add docs
        git commit -m 'Generate and update documentation'
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}